version: "3.8"
services:
  backend:
    build:
      context: ./
    ports:
      - "8000:8000"
    volumes:
      - ./app
      - node_modules
    env_file:
      - /home/aritra/Flipr/EmployeeManagement/.env
  client:
    build:
      context: client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
      - client/node_modules
    stdin_open: true
    tty: true
volumes:
  logs:
